//using System;
//using System.Windows.Forms;
//using System.Drawing;

namespace GUI_WinForm_Button
{
    public class MainClass : System.Windows.Forms.Form
    {
        private System.Windows.Forms.Button red;
        private System.Windows.Forms.Button blue;
        private System.Windows.Forms.Button green;

        public MainClass() : base()
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        // InitializeComponent is a helper method for the constructor.
        // It is included for consistency with code that is
        // auto-generated by the Windows Forms designer in Visual Studio.
        private void InitializeComponent()
        {

            // A delegate for the click event of a button. The argument to
            // the constructor contains a reference to the method that performs the
            // event handling logic.  
            System.EventHandler handler = new System.EventHandler(this.button_Click);

            // Creates three buttons, sets their properties, and attaches  
            // an event handler to each button.  

            red = new System.Windows.Forms.Button();
            red.Text = "Red";
            red.Location = new System.Drawing.Point(100, 50);
            red.Size = new System.Drawing.Size(50, 50);
            red.Click += handler;
            Controls.Add(red);

            blue = new System.Windows.Forms.Button();
            blue.Text = "Blue";
            blue.Location = new System.Drawing.Point(100, 100);
            blue.Size = new System.Drawing.Size(50, 50);
            blue.Click += handler;
            Controls.Add(blue);

            green = new System.Windows.Forms.Button();
            green.Text = "Green";
            green.Location = new System.Drawing.Point(100, 150);
            green.Size = new System.Drawing.Size(50, 50);
            green.Click += handler;
            Controls.Add(green);
        }

        // Event handler.  
        private void button_Click(object sender, System.EventArgs e)
        {
            if (sender == red) this.BackColor = System.Drawing.Color.FromArgb(0xFF, 0x00, 0xFF); //Red;
            else if (sender == blue) this.BackColor = System.Drawing.Color.Blue;
            else this.BackColor = System.Drawing.Color.Green;
        }
        // The STAThreadAttribute informs the common language runtime that  
        // Windows Forms uses the single-threaded apartment model.  
        [System.STAThread]
        public static void Main(string[] args)
        {
            System.Windows.Forms.Application.Run(new MainClass());
        }

    }
}
